### ISSUE TITLE
Fix bug causing mobs to jump off platforms

### ISSUE THREAD

**Issue by atnight348** [atnight348/Lidium#86]

**Comment by v3921358** [comment]
foot hold Error

**Comment by atnight348** [comment]
> foot hold Error

I believe this is correct from my experience with debugging it in version 83

**Comment by v3921358** [comment]
"foothold FallStart" which is what I mean

**Comment by atnight348** [comment]
Thank you, I will attempt a fix with this new information

**Comment by atnight348** [comment]
https://github.com/atnight348/Lidium/pull/147/commits/05c6e05361f762b8e34ab44d8e6aa99327b66a97
